name: Check for Changeset

env:
  MIDNIGHT_GH_USER: ${{ secrets.GH_USERNAME }}
  MIDNIGHT_GH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_READ }}
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-changeset:
    if: ${{ !startsWith(github.head_ref, 'changeset-release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Check tool versions
        run: |
          bun --version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Verify that a changeset exists
        run: |
          bun run changeset:check
